name: Deploy Prod

on:
  workflow_run:
    workflows: ["Deploy Dev"]
    types: [completed]

concurrency:
  group: cdk-prod
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'eu-west-1' }}

jobs:
  e2e:
    name: E2E
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout same commit as Dev
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            src/frontend/package-lock.json

      - name: Install deps
        working-directory: src/frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: src/frontend
        run: npx playwright install --with-deps

      - name: Run Playwright E2E
        working-directory: src/frontend
        env:
          E2E_BASE_URL: ${{ vars.E2E_BASE_URL }}
          VITE_USER_POOL_ID: ${{ secrets.VITE_USER_POOL_ID_DEV }}
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID_DEV }}
          VITE_API_URL: ${{ vars.API_URL_DEV }}
        run: npx playwright test --reporter=line

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: src/frontend/e2e/playwright-report
          retention-days: 7

  deploy:
    name: Deploy to prod
    needs: e2e
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout same commit as Dev
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node (backend & infra)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            src/backend/package-lock.json
            infrastructure/package-lock.json

      - name: Install deps (backend)
        working-directory: src/backend
        run: npm ci

      - name: Install deps (infra)
        working-directory: infrastructure
        run: npm ci

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK synth (prod)
        working-directory: infrastructure
        run: npx cdk synth -c env=prod

      - name: CDK deploy (prod)
        working-directory: infrastructure
        run: npx cdk deploy --all -c env=prod --require-approval=never
