name: Tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-frontend:
    name: Lint frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: src/frontend/package-lock.json
      - name: Install deps (frontend)
        working-directory: src/frontend
        run: npm ci
      - name: Run lint
        working-directory: src/frontend
        run: npm run lint

  test-backend:
    name: Unit tests (backend)   # 👈 mantiene el mismo nombre requerido en la regla
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: src/backend/package-lock.json
      - name: Install deps (backend)
        working-directory: src/backend
        run: npm ci
      - name: Run unit tests (backend)
        working-directory: src/backend
        run: npm run test:unit

  test-infra:
    name: Unit tests (infrastructure)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: infrastructure/package-lock.json
      - name: Install deps (backend)
        working-directory: src/backend
        run: npm ci
      - name: Install deps (infra)
        working-directory: infrastructure
        run: npm ci
      - name: Run unit tests (infra)
        working-directory: infrastructure
        run: npm run test:unit
